# Generated by Django 2.2 on 2019-05-01 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
